# Generated by Django 5.2.6 on 2025-09-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the product name', max_length=200)),
                ('sku', models.CharField(help_text='Enter the Stock Keeping Unit (SKU)', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Enter the available quantity')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
