# Generated by Django 5.2.7 on 2025-11-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_price_alter_purchaseorderitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, help_text='Enter the product name', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, help_text='Enter the Stock Keeping Unit (SKU)', max_length=100, unique=True),
        ),
    ]
