# Generated by Django 5.2.7 on 2025-11-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_name_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='last_purchase_date',
            field=models.DateTimeField(blank=True, help_text='Date this product was last restocked.', null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVATED', 'Deactivated')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='last_purchase_date',
            field=models.DateTimeField(blank=True, help_text='Date this product was last restocked.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVATED', 'Deactivated')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Price per item at the time of a 'Stock Out' transaction.", max_digits=10, null=True),
        ),
    ]
