# Generated by Django 5.2.7 on 2025-11-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_historicalproduct_last_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'ordering': ['-timestamp'], 'permissions': [('can_adjust_stock', 'Can adjust stock quantities'), ('can_view_history', 'Can view product edit history'), ('can_view_reports', 'Can view and generate reports')]},
        ),
    ]
