# Generated by Django 5.2.8 on 2025-11-20 02:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_stocktransaction_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='transaction_reason',
            field=models.CharField(choices=[('SALE', 'Sale (Revenue)'), ('PO', 'Purchase Order (Restock)'), ('DAMAGE', 'Damaged / Expired (Loss)'), ('INTERNAL', 'Internal Use / Demo'), ('CORRECTION', 'Inventory Correction / Mistake'), ('RETURN', 'Customer Return'), ('OTHER', 'Other')], default='SALE', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_type', 'timestamp'], name='inventory_s_transac_1dac81_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_reason'], name='inventory_s_transac_cbfda6_idx'),
        ),
    ]
