# Generated by Django 5.2.8 on 2025-11-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stocktransaction_transaction_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='notes',
            field=models.TextField(blank=True, help_text='Reason for the transaction', null=True),
        ),
    ]
