# Generated by Django 5.2.8 on 2025-11-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_stocktransaction_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (In Delivery)'), ('COMPLETED', 'Arrived (Ready to Receive)'), ('RECEIVED', 'Received & Stocked'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10),
        ),
    ]
