# Generated by Django 5.2.8 on 2025-11-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_reason',
            field=models.CharField(choices=[('SALE', 'Sale (Revenue)'), ('PO', 'Purchase Order (Restock)'), ('DAMAGE', 'Damaged / Expired (Loss)'), ('INTERNAL', 'Internal Use / Demo'), ('CORRECTION', 'Inventory Correction / Mistake'), ('INITIAL', 'Initial Stock'), ('RETURN', 'Customer Return'), ('OTHER', 'Other')], default='SALE', max_length=20),
        ),
    ]
