# Generated by Django 5.2.10 on 2026-02-03 09:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_stocktransaction_transaction_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the price in PHP', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the price in PHP', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per item in PHP at time of purchase', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Price per item at the time of a 'Stock Out' transaction.", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_reason',
            field=models.CharField(choices=[('SALE', 'Sale (Revenue)'), ('PO', 'Purchase Order (Restock)'), ('DAMAGE', 'Damaged / Expired (Loss)'), ('INTERNAL', 'Internal Use / Demo'), ('CORRECTION', 'Inventory Correction / Mistake'), ('RETURN', 'Customer Return'), ('INITIAL', 'Initial Stock'), ('OTHER', 'Other')], default='SALE', max_length=20),
        ),
    ]
