# Generated by Django 5.2.10 on 2026-02-03 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_historicalproduct_price_alter_product_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('change_given', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'POS Sale',
                'verbose_name_plural': 'POS Sales',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='pos_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.possale'),
        ),
    ]
