# Generated by Django 5.2.10 on 2026-02-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_possale_stocktransaction_pos_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
