# Generated by Django 6.0.2 on 2026-02-10 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_customer_possale_due_date_possale_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='notes',
            field=models.TextField(blank=True, help_text='Transaction notes or description'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
