# Generated by Django 6.0.2 on 2026-02-10 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_possale_notes_alter_possale_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydraulicSow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('hose_type', models.CharField(blank=True, max_length=100)),
                ('diameter', models.CharField(blank=True, max_length=50)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('application', models.CharField(blank=True, max_length=200)),
                ('fitting_a', models.CharField(blank=True, max_length=100)),
                ('fitting_b', models.CharField(blank=True, max_length=100)),
                ('orientation', models.IntegerField(blank=True, help_text='Angle in degrees', null=True)),
                ('protection', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sows', to='inventory.customer')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
