# Generated by Django 5.2.11 on 2026-02-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_historicalproduct_image_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
