# Generated by Django 5.2.11 on 2026-02-17 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_supplier_supplier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='sale_paid',
            field=models.ForeignKey(blank=True, help_text='The specific credit sale this payment is for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to='inventory.possale'),
        ),
    ]
