# Generated by Django 5.2.11 on 2026-02-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_hydraulicsow_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydraulicsow',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of the customization service.', max_digits=10, null=True),
        ),
    ]
