# Generated by Django 5.2.11 on 2026-02-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_hydraulicsow_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydraulicsow',
            name='sow_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
