# Generated by Django 5.2.11 on 2026-05-09 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_refundhistory_alter_stocktransaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=10),
        ),
        migrations.CreateModel(
            name='CancellationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for cancelling the debt.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pos_sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_reason', to='inventory.possale')),
            ],
            options={
                'verbose_name': 'Cancellation Reason',
                'verbose_name_plural': 'Cancellation Reasons',
                'ordering': ['-timestamp'],
            },
        ),
    ]
