# Generated by Django 5.2.11 on 2026-05-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_purchaseorderreceiptlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possale',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='COMPLETED', max_length=10),
        ),
    ]
