# Generated by Django 5.2.11 on 2026-05-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_purchaseorderreceiptlog'),
        ('inventory', '0036_alter_possale_status'),
    ]

    operations = [
    ]
